### ISSUE TITLE
https CATTLE_URL not working?

### ISSUE THREAD

**Issue by marcovn** [ampedandwired/rancher-reaper#1]
Hi,

Great work you have done here. When trying to deploy the container on one of our environments we ran in to the issue that we have our rancher server setup on https only.

You get a stack trace like the one below. Opening the http port (as a workaround) fixes that but not very good for our security policy. Unfortunately my Ruby skills are not that great as I would tried to fix it.

Thanks,

E, [2016-09-30T11:31:10.430732 #5] ERROR -- : 784: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
30-9-2016 13:31:10<html><head>
30-9-2016 13:31:10<title>400 Bad Request</title>
30-9-2016 13:31:10</head><body>
30-9-2016 13:31:10<h1>Bad Request</h1>
30-9-2016 13:31:10<p>Your browser sent a request that this server could not understand.<br />
30-9-2016 13:31:10Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
30-9-2016 13:31:10 Instead use the HTTPS scheme to access this URL, please.<br />
30-9-2016 13:31:10</p>
30-9-2016 13:31:10<hr>
30-9-2016 13:31:10<address>Apache/2.4.7 (Ubuntu) Server at rancher.domain Port 443</address>
30-9-2016 13:31:10</body></html>
30-9-2016 13:31:10' (JSON::ParserError)
30-9-2016 13:31:10/usr/local/lib/ruby/2.3.0/json/common.rb:156:in `parse'
30-9-2016 13:31:10/usr/local/lib/ruby/2.3.0/json/common.rb:156:in`parse'
30-9-2016 13:31:10/usr/src/app/rancher_api.rb:17:in `get'
30-9-2016 13:31:10/usr/src/app/rancher_api.rb:23:in`block (2 levels) in get_all'
30-9-2016 13:31:10/usr/src/app/rancher_api.rb:22:in `loop'
30-9-2016 13:31:10/usr/src/app/rancher_api.rb:22:in`block in get_all'
30-9-2016 13:31:10/usr/src/app/reaper.rb:37:in `each'
30-9-2016 13:31:10/usr/src/app/reaper.rb:37:in`each'
30-9-2016 13:31:10/usr/src/app/reaper.rb:37:in `reap_hosts'
30-9-2016 13:31:10/usr/src/app/reaper.rb:21:in`run'
30-9-2016 13:31:10config.ru:24:in `block (2 levels) in <main>
`

**Comment by ampedandwired** [comment]
Just pushed a fix (hopefully - I haven't got an https enabled Rancher handy). Could you try with the "latest" image in Docker Hub? If it's all good I'll cut another release.

**Comment by marcovn** [comment]
Hi Charles,

Thanks for your fix. I can happily report it is working for us in our
environments. Very useful as we recycle our AWS based rancher hosts
frequently.

**Comment by ampedandwired** [comment]
Glad to hear it. I've tagged a new release, v0.1.1.

**Comment by marcovn** [comment]
Awesome, I will deploy that tag and keep you posted.
