### ISSUE TITLE
aws_sdk bug prevents rancher-reaper from removing hosts

### ISSUE THREAD

**Issue by cbarbour** [ampedandwired/rancher-reaper#11]
It appears there is an issue with the AWS SDK which prevents Rancher Reaper from reaping hosts that have been terminated for more than 1 hour.

https://github.com/aws/aws-sdk-ruby/issues/1449

As far as I can tell, this isn't really a flaw in rancher-reaper, other than perhaps to catch and more cleanly handle the NoMethodError.

This is what shows up in my logs:

```
I, [2017-03-17T01:46:00.182630 #7]  INFO -- : Reaping terminated AWS hosts...
E, [2017-03-17T01:46:00.511135 #7] ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
/usr/local/bundle/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
/usr/src/app/reaper.rb:79:in `host_terminated?'
/usr/src/app/reaper.rb:45:in `block in reap_hosts'
/usr/src/app/rancher_api.rb:20:in `yield'
/usr/src/app/rancher_api.rb:20:in `block (3 levels) in get_all'
/usr/src/app/rancher_api.rb:20:in `each'
/usr/src/app/rancher_api.rb:20:in `block (2 levels) in get_all'
/usr/src/app/rancher_api.rb:17:in `loop'
/usr/src/app/rancher_api.rb:17:in `block in get_all'
/usr/src/app/reaper.rb:44:in `each'
/usr/src/app/reaper.rb:44:in `each'
/usr/src/app/reaper.rb:44:in `reap_hosts'
/usr/src/app/reaper.rb:24:in `run'
config.ru:24:in `block (2 levels) in <main>'
```

Otherwise, the solution will probably require building a new container once the upstream bug is resolved.

**Comment by ampedandwired** [comment]
Fixed in v0.4.0. It now uses `instance.exists?` to test whether the instance was returned by the API before checking the instance state.
