### ISSUE TITLE
Missing region error while reaping terminated host

### ISSUE THREAD

**Issue by Troyhy** [ampedandwired/rancher-reaper#7]
I have Rancher setup in eu-west-1b region
  
hosts have labels setup like suggested in dockumentation
aws.availability_zone=eu-west-1b
aws.instance_id=i-63ba5cf5

and when I terminate host this error shows up:

11/11/2016 10:09:36I, [2016-11-11T08:09:36.505244 #5]  INFO -- : Reaping terminated AWS hosts...
11/11/2016 10:09:36E, [2016-11-11T08:09:36.545251 #5] ERROR -- : missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize'
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/seahorse/client/base.rb:84:in `block in after_initialize'
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/seahorse/client/base.rb:83:in `each'
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/seahorse/client/base.rb:83:in `after_initialize'
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/seahorse/client/base.rb:21:in `initialize'
11/11/2016 10:09:36/usr/local/bundle/gems/aws-sdk-core-2.6.3/lib/seahorse/client/base.rb:105:in `new'
11/11/2016 10:09:36/usr/src/app/reaper.rb:119:in `valid_regions'
11/11/2016 10:09:36/usr/src/app/reaper.rb:109:in `region'
11/11/2016 10:09:36/usr/src/app/reaper.rb:97:in `has_aws_tags?'
11/11/2016 10:09:36/usr/src/app/reaper.rb:71:in `host_terminated?'
11/11/2016 10:09:36/usr/src/app/reaper.rb:45:in `block in reap_hosts'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:20:in `yield'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:20:in `block (3 levels) in get_all'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:20:in `each'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:20:in `block (2 levels) in get_all'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:17:in `loop'
11/11/2016 10:09:36/usr/src/app/rancher_api.rb:17:in `block in get_all'
11/11/2016 10:09:36/usr/src/app/reaper.rb:44:in `each'
11/11/2016 10:09:36/usr/src/app/reaper.rb:44:in `each'
11/11/2016 10:09:36/usr/src/app/reaper.rb:44:in `reap_hosts'
11/11/2016 10:09:36/usr/src/app/reaper.rb:24:in `run'
11/11/2016 10:09:36config.ru:24:in `block (2 levels) in <main>'

**Comment by Troyhy** [comment]
Inspecting further I fount this function to be the problem:

 def region(host)
    region = nil
    availability_zone = host["labels"]["aws.availability_zone"]
    if availability_zone
      region = availability_zone[0..-2]

where eu-west-1b gets converted to "eu-west-" and not "eu-west"

If I knew howto code ruby, I would implement this this with rexexp -> http://regexr.com/3ekk5 
where first match group is the region r'/(._)-._?$/'

**Comment by ampedandwired** [comment]
Sorry for the delayed response here. If you set the environment variable `AWS_DEFAULT_REGION=eu-west-1` in the container it should fix this problem.

I don't think the code you pointed out is the culprit, although I should still probably change the code so that setting the environment variable above is not necessary. I'll do this when I get some time, in the meantime I've updated the README to include setting AWS_DEFAULT_REGION.

**Comment by ampedandwired** [comment]
Fix released in 0.2.1. Should be no longer necessary to specify AWS_DEFAULT_REGION variable.

**Comment by Troyhy** [comment]
Latest version gives me this stacktrace

22/11/2016 13:27:49I, [2016-11-22T11:27:49.732594 #10]  INFO -- : Reaping terminated AWS hosts...
22/11/2016 13:27:49E, [2016-11-22T11:27:49.835944 #10] ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
22/11/2016 13:27:49/usr/local/bundle/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
22/11/2016 13:27:49/usr/src/app/reaper.rb:74:in `host_terminated?'
22/11/2016 13:27:49/usr/src/app/reaper.rb:44:in `block in reap_hosts'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:20:in `yield'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:20:in `block (3 levels) in get_all'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:20:in `each'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:20:in `block (2 levels) in get_all'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:17:in `loop'
22/11/2016 13:27:49/usr/src/app/rancher_api.rb:17:in `block in get_all'
22/11/2016 13:27:49/usr/src/app/reaper.rb:43:in `each'
22/11/2016 13:27:49/usr/src/app/reaper.rb:43:in `each'
22/11/2016 13:27:49/usr/src/app/reaper.rb:43:in `reap_hosts'
22/11/2016 13:27:49/usr/src/app/reaper.rb:24:in `run'
22/11/2016 13:27:49config.ru:24:in `block (2 levels) in <main>'

Labels: 
aws.availability_zone=eu-west-1c
aws.instance_id=i-9195f11a
